name: Build

on:
  push:
    paths:
      - ".github/workflows/**"
      - "src/**"
      - "theme/**"
      - "book.toml"

permissions:
  pages: write
  id-token: write

jobs:
  html:
    name: Build and deploy to GitHub Pages

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Write variable to environment
        run: echo -e "BUILD_TIME=$(TZ=Asia/Shanghai date -Iseconds)" >> "$GITHUB_ENV"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install mdBook
        uses: baptiste0928/cargo-install@v2
        with:
          crate: mdbook
          git: https://github.com/Zh40Le1ZOOB/mdBook

      - name: Add version info
        run: |
          cat >> src/README.md << EOF
          ## 版本信息
          \`\`\`
          提交 SHA：$GITHUB_SHA
          构建时间：$BUILD_TIME
          \`\`\`
          EOF

      - name: Build book
        run:  mdbook build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: book/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3

  epub:
    name: Build and upload EPUB

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install mdbook-epub
        uses: baptiste0928/cargo-install@v2
        with:
          crate: mdbook-epub
          git: https://github.com/Michael-F-Bryan/mdbook-epub

      - name: Add EPUB options
        run: |
          cat >> book.toml << EOF
          [output.epub]
          additional-css = ["theme/style.css"]
          use-default-css = false
          cover-image = "images/cover.jpg"
          no-section-label = true
          curly-quotes = true
          EOF

      - name: Add version info
        run: |
          cat >> src/README.md << EOF
          ## 版本信息
          \`\`\`
          提交 SHA：$GITHUB_SHA
          构建时间：$BUILD_TIME
          \`\`\`
          EOF

      - name: Build EPUB
        run: mdbook-epub -s true

      - name: Rename EPUB file
        run: mv book/epub/*.epub book/epub/药娘的天空-$GITHUB_SHA.epub

      - name: Upload EPUB artifact
        uses: actions/upload-artifact@v4
        with:
          name: EPUB
          path: book/epub/*.epub
          compression-level: 9

  pdf:
    name: Build and upload PDF

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install mdBook
        uses: baptiste0928/cargo-install@v2
        with:
          crate: mdbook
          git: https://github.com/Zh40Le1ZOOB/mdBook

      - name: Install mdbook-compress
        uses: baptiste0928/cargo-install@v2
        with:
          crate: mdbook-compress

      - name: Add PDF options
        run: |
          cat >> book.toml << EOF
          [output.compress]
          highlight = "none"
          EOF

      - name: Add version info
        run: |
          cat >> src/README.md << EOF
          ## 版本信息
          \`\`\`
          提交 SHA：$GITHUB_SHA
          构建时间：$BUILD_TIME
          \`\`\`
          EOF

      - name: Build PDF
        run: mdbook build

      - name: Rename PDF file
        run: mv book/compress/*.pdf book/compress/药娘的天空-$GITHUB_SHA.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: book/compress/*.pdf
          compression-level: 9
